-- Run in Supabase SQL Editor
-- Purpose: archive Zoom/Calendly dashboard snapshots + invitee details only when changed.

create table if not exists public.live_sessions_snapshots (
  id bigint generated by default as identity primary key,
  generated_at timestamptz not null default now(),
  snapshot_hash text not null unique,
  payload jsonb not null
);

create index if not exists idx_live_sessions_snapshots_generated_at
  on public.live_sessions_snapshots (generated_at desc);

create table if not exists public.live_session_invitees_archive (
  id bigint generated by default as identity primary key,
  snapshot_hash text not null references public.live_sessions_snapshots(snapshot_hash) on delete cascade,
  invitee_uri text not null,
  event_uri text not null,
  email text not null,
  name text,
  status text,
  no_show boolean not null default false,
  canceled boolean not null default false,
  timezone text,
  text_reminder_number text,
  phone_number text,
  cancel_url text,
  reschedule_url text,
  created_at_source timestamptz,
  updated_at_source timestamptz,
  questions_and_answers jsonb not null default '[]'::jsonb,
  inserted_at timestamptz not null default now(),
  unique (snapshot_hash, invitee_uri)
);

create index if not exists idx_live_session_invitees_email
  on public.live_session_invitees_archive (email);

create index if not exists idx_live_session_invitees_event_uri
  on public.live_session_invitees_archive (event_uri);
